import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
//import for openAi
import { Configuration, OpenAIApi } from "openai";
import { text } from 'node:stream/consumers';
import { render } from 'react-dom';
import { stat } from 'node:fs';
import { PuffLoader } from 'react-spinners';

import { useState } from 'react';
let showLoader = false
export default function Home() {

  const [showLoader, setShowLoader] = useState(false)

  return (
    <div className={styles.container}>
      <Head>
        <title>the AI checker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div id="textbox">
          <textarea name="demo-message" id="demo-message" placeholder="Enter your writing here" rows={20} style={{ color: 'white', marginRight: '100px', width: "600px" }}></textarea>
        </div>

        <button style={{ color: 'white', marginRight: '100px' }} onClick={async function () {
          setShowLoader(true)
          const respose = await fetch("api/backend")
          console.log(respose)
          const data = await respose.json()
          const output = data.data
          const paragraph: any = document.getElementById("output")
          paragraph.innerText = output
          console.log(data)
          setShowLoader(false)

        }}>click me</button>
        <div style={{ color: 'white', fontSize: '18px' }}>
          <p id="output"></p>
        </div>


        {showLoader ? <PuffLoader color="#36d7b7" /> : null}



      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>

  )

}
