import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
//import for openAi
import { Configuration, OpenAIApi } from "openai";


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>the AI checker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <p id="output"></p>
        	<div>
						<textarea name="demo-message" id="demo-message" placeholder="Enter your writing here" rows="25"></textarea>
					</div>
        <button onClick={async function () {
          const respose = await fetch("api/backend")
          console.log(respose)
          const data = await respose.json()
          const output = data.data
          const paragraph: any = document.getElementById("output")
          paragraph.innerText = output
          console.log(data)
        }}>click me</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
